fix: `https-proxy-agent@^5.0.0` to fix node@15 `ERR_INVALID_PROTOCOL`
With `nodejs@15.0.1`, install puppeteer with `https_proxy` set will cause error like:
```
> puppeteer@5.4.1 install /home/dr/Git/dr-js/node_modules/puppeteer
> node install.js

ERROR: Failed to set up Chromium r809590! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:258:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at httpRequest (/home/dr/Git/dr-js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:488:17)
    at downloadFile (/home/dr/Git/dr-js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:357:21)
    at BrowserFetcher.download (/home/dr/Git/dr-js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:239:19)
    at async downloadBrowser (/home/dr/Git/dr-js/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:48:5) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

The related issue is at https://github.com/TooTallNate/node-agent-base/pull/47,
  from package `agent-base` under `https-proxy-agent`

And the version bump is for `Refactor to TypeScript`: https://github.com/TooTallNate/node-https-proxy-agent/compare/4.0.0...5.0.0